import React, { useEffect, useRef, useState } from "react";
import { api } from "./api";
import "./pilot-onboarding.css";

type Setup = {
  organizationName: string; workflowName: string; primaryChannel: "microsoft_365_email" | "google_email" | "whatsapp" | "api";
  identityProvider: "entra" | "google" | "okta" | "other"; systemOfRecord: "salesforce" | "hubspot" | "zendesk" | "dynamics" | "custom" | "none" | "other";
  hostingRegion: "eu_germany" | "eu_ireland" | "eu_other"; targetStartDate: string; teamNames: [string,string]; expectedUsers: number; monthlyCases: number;
  retentionDays: 30 | 60 | 90; pilotOwnerName: string; pilotOwnerEmail: string; technicalContactName: string; technicalContactEmail: string;
  accessEnvironment: "sandbox" | "test_account" | "production_approved"; dataExclusionsConfirmed: boolean; version?: number;
};
type Response = { setup: Setup | null; state: string; relayGates?: string[]; nextStep: string };

const start = new Date(Date.now() + 14 * 86400000).toISOString().slice(0,10);
const empty: Setup = { organizationName:"",workflowName:"",primaryChannel:"microsoft_365_email",identityProvider:"entra",systemOfRecord:"none",hostingRegion:"eu_germany",targetStartDate:start,teamNames:["",""],expectedUsers:8,monthlyCases:500,retentionDays:30,pilotOwnerName:"",pilotOwnerEmail:"",technicalContactName:"",technicalContactEmail:"",accessEnvironment:"sandbox",dataExclusionsConfirmed:false };
const channelLabels = { microsoft_365_email:"Microsoft 365 E-Mail",google_email:"Google Workspace E-Mail",whatsapp:"WhatsApp Business",api:"Eigene API" };
const idpLabels = { entra:"Microsoft Entra",google:"Google Workspace",okta:"Okta",other:"Anderer IdP" };
const systemLabels = { salesforce:"Salesforce",hubspot:"HubSpot",zendesk:"Zendesk",dynamics:"Microsoft Dynamics",custom:"Eigenes System",none:"Keines",other:"Anderes" };
const gateLabels: Record<string,string> = { managed_postgres_rls:"PostgreSQL & Tenant-Isolation",oidc_connection:"OIDC-Verbindung",secret_store_rotation:"Secret Store & Rotation",provider_adapter_fixture:"Provideradapter-Fixtures",shadow_run_100:"Shadow Run mit 100 Events",backup_restore:"Backup & Restore" };

export function PilotOnboarding() {
  const [step,setStep]=useState(0); const [value,setValue]=useState<Setup>(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<Response|null>(null); const form=useRef<HTMLFormElement>(null);
  useEffect(()=>{ api<Response>("/api/v1/pilot-onboarding").then(response=>{ if(response.setup) setValue(response.setup); setResult(response.setup?response:null); }).catch(err=>setError(err.message)).finally(()=>setLoading(false)); },[]);
  const update=<K extends keyof Setup>(key:K,next:Setup[K])=>setValue(current=>({...current,[key]:next}));
  const next=()=>{ if(form.current?.reportValidity()) setStep(current=>Math.min(4,current+1)); };
  const submit=async()=>{ setSaving(true); setError(""); try { const response=await api<Response>("/api/v1/pilot-onboarding",{method:"PUT",headers:{"If-Match":String(value.version??0)},body:JSON.stringify({...value,version:undefined})}); setValue(response.setup!); setResult(response); } catch(err){setError((err as Error).message);} finally{setSaving(false);} };
  if(loading) return <div className="setup-loading">Ersteinrichtung wird geladen …</div>;
  if(result?.setup && result.state==="relay_review_required") return <section className="setup-view"><header className="setup-header"><span className="eyebrow">Pilot Control Plane</span><h1>Einrichtung angefordert</h1><p>{result.nextStep}</p></header><div className="setup-success"><div className="success-check">✓</div><h2>{result.setup.organizationName}</h2><p><strong>{channelLabels[result.setup.primaryChannel]}</strong> · {result.setup.workflowName} · Startziel {new Intl.DateTimeFormat("de-DE").format(new Date(`${result.setup.targetStartDate}T12:00:00`))}</p><div className="gate-preview"><span className="eyebrow">Von Relay zu prüfen</span>{(result.relayGates??[]).map(gate=><div key={gate}><span/> {gateLabels[gate]??gate}</div>)}</div><button className="secondary" onClick={()=>{setResult(null);setStep(0);}}>Angaben bearbeiten</button></div></section>;
  const titles=["Pilot festlegen","Eingangskanal","Anmeldung & Kontakte","Daten & Betrieb","Prüfen & anfordern"];
  return <section className="setup-view"><header className="setup-header"><span className="eyebrow">Pilot Control Plane</span><h1>Ersteinrichtung</h1><p>Ein Prozess, ein Eingangskanal, zwei Teams. Secrets und echte Kommunikationsdaten gehören ausdrücklich nicht in dieses Formular.</p></header><div className="setup-shell"><ol className="setup-steps">{titles.map((title,index)=><li className={index===step?"active":index<step?"done":""} key={title}><span>{index<step?"✓":index+1}</span><div><strong>{title}</strong><small>{index===step?"In Bearbeitung":index<step?"Vollständig":"Ausstehend"}</small></div></li>)}</ol><form ref={form} className="setup-form" onSubmit={event=>{event.preventDefault();void submit();}}><div className="setup-form-head"><span>Schritt {step+1} von 5</span><h2>{titles[step]}</h2></div>
  {step===0&&<div className="setup-fields"><label className="wide">Unternehmen<input required minLength={2} value={value.organizationName} onChange={e=>update("organizationName",e.target.value)} placeholder="z. B. Muster Service GmbH"/></label><label className="wide">Abgegrenzter Pilotprozess<input required minLength={3} value={value.workflowName} onChange={e=>update("workflowName",e.target.value)} placeholder="z. B. Störungsmeldung bis bestätigte Übergabe"/></label><label>Team 1<input required minLength={2} value={value.teamNames[0]} onChange={e=>update("teamNames",[e.target.value,value.teamNames[1]])}/></label><label>Team 2<input required minLength={2} value={value.teamNames[1]} onChange={e=>update("teamNames",[value.teamNames[0],e.target.value])}/></label><label>Geplanter Start<input required type="date" value={value.targetStartDate} onChange={e=>update("targetStartDate",e.target.value)}/></label></div>}
  {step===1&&<div className="setup-fields"><label>Eingangskanal<select value={value.primaryChannel} onChange={e=>update("primaryChannel",e.target.value as Setup["primaryChannel"])}>{Object.entries(channelLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Zugangsumgebung<select value={value.accessEnvironment} onChange={e=>update("accessEnvironment",e.target.value as Setup["accessEnvironment"])}><option value="sandbox">Sandbox</option><option value="test_account">Isoliertes Testkonto</option><option value="production_approved">Produktivzugang freigegeben</option></select></label><label>Führendes System<select value={value.systemOfRecord} onChange={e=>update("systemOfRecord",e.target.value as Setup["systemOfRecord"])}>{Object.entries(systemLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><div className="setup-callout wide">Relay liest im Pilot genau einen Eingangskanal. Externes Senden ist nicht enthalten. Die Auswahl löst noch keine Verbindung aus.</div></div>}
  {step===2&&<div className="setup-fields"><label className="wide">Identity Provider<select value={value.identityProvider} onChange={e=>update("identityProvider",e.target.value as Setup["identityProvider"])}>{Object.entries(idpLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Pilotverantwortliche Person<input required value={value.pilotOwnerName} onChange={e=>update("pilotOwnerName",e.target.value)}/></label><label>Geschäftliche E-Mail<input required type="email" value={value.pilotOwnerEmail} onChange={e=>update("pilotOwnerEmail",e.target.value)}/></label><label>Technischer Kontakt<input required value={value.technicalContactName} onChange={e=>update("technicalContactName",e.target.value)}/></label><label>Geschäftliche E-Mail<input required type="email" value={value.technicalContactEmail} onChange={e=>update("technicalContactEmail",e.target.value)}/></label><div className="setup-callout wide">Keine Client Secrets, Tokens oder OIDC-Subjects eintragen. Diese werden später über den sicheren Verbindungsprozess eingerichtet.</div></div>}
  {step===3&&<div className="setup-fields"><label>Hostingregion<select value={value.hostingRegion} onChange={e=>update("hostingRegion",e.target.value as Setup["hostingRegion"])}><option value="eu_germany">EU · Deutschland</option><option value="eu_ireland">EU · Irland</option><option value="eu_other">Andere EU-Region</option></select></label><label>Vorgesehene Nutzer<input required type="number" min={2} max={50} value={value.expectedUsers} onChange={e=>update("expectedUsers",Number(e.target.value))}/></label><label>Cases pro Monat<input required type="number" min={1} max={10000} value={value.monthlyCases} onChange={e=>update("monthlyCases",Number(e.target.value))}/></label><label>Aufbewahrung<select value={value.retentionDays} onChange={e=>update("retentionDays",Number(e.target.value) as Setup["retentionDays"])}><option value={30}>30 Tage</option><option value={60}>60 Tage</option><option value={90}>90 Tage</option></select></label><label className="setup-confirm wide"><input required type="checkbox" checked={value.dataExclusionsConfirmed} onChange={e=>update("dataExclusionsConfirmed",e.target.checked)}/><span>Im Pilot werden keine besonderen Kategorien personenbezogener Daten, Zahlungsdaten, Zugangsdaten oder unkontrollierten Anhänge verarbeitet.</span></label></div>}
  {step===4&&<div className="setup-review"><Review title="Pilot" rows={[["Unternehmen",value.organizationName],["Prozess",value.workflowName],["Teams",value.teamNames.join(" · ")],["Start",value.targetStartDate]]}/><Review title="Integration" rows={[["Kanal",channelLabels[value.primaryChannel]],["Umgebung",value.accessEnvironment],["System",systemLabels[value.systemOfRecord]],["Anmeldung",idpLabels[value.identityProvider]]]}/><Review title="Betrieb" rows={[["Region",value.hostingRegion],["Nutzer",String(value.expectedUsers)],["Cases/Monat",String(value.monthlyCases)],["Retention",`${value.retentionDays} Tage`]]}/><div className="setup-warning"><strong>Dadurch erfolgt kein Go-live.</strong><span>Relay prüft anschließend Datenbank, OIDC, Secret Store, Provideradapter, Shadow Run und Backup/Restore.</span></div></div>}
  {error&&<div className="error-banner">{error}</div>}<div className="setup-actions">{step>0&&<button type="button" className="secondary" onClick={()=>setStep(current=>current-1)}>Zurück</button>}<span/>{step<4?<button type="button" className="primary" onClick={next}>Weiter</button>:<button className="primary" disabled={saving}>{saving?"Wird angefordert …":"Einrichtung anfordern"}</button>}</div></form></div></section>;
}

function Review({title,rows}:{title:string;rows:string[][]}){return <div className="review-block"><h3>{title}</h3><dl>{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div>}
